### PR TITLE
fix: build failed, lost jeep-sqlite package

### PR DESCRIPTION
**Pull request by sabakugaara**

### CODE REVIEW

**Comment by jepiqueau** [comment]
@sabakugaara This is not required, delete your node_modules folder and the package-lock.json and do npm install. it should work. jeep-sqlite is loaded in node_modules as a dependency of @capacitor-community/sqlite

**Comment by sabakugaara** [comment]
> 

OK, I use pnpm and manually install it, otherwise ionic will fail to build.

**Comment by jepiqueau** [comment]
@sabakugaara i tested with npm and yarn and it works, i also tested is with pnpm and here you right but you must also pnpm i --save sql.js otherwise it will not work. So i will not accept to merge the PR but i will modify the doc of capacitor-community/sqlite to add for pnpm these two supplementary installs. Do you agree with that?

**Comment by sabakugaara** [comment]
Thank you! I agree.

**Pull request closed without merging**
